apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service

spec:
  selector:
    matchLabels:
      app: product-service
  template:
      metadata:
        labels:
          app: product-service
      spec:
        resources:
          - requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"

        containers:
          - name: product-service
            image: ram1uj/ecom-app-product-service
            ports:
              - containerPort: 8100