apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
    selector:
        app: product-service
    ports:
        - protocol: TCP
          port: 8100
          targetPort: 8100
    type: NodePort