apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-recipes-deployment
  namespace: dev
spec:

    replicas: 3
    selector:
        matchLabels:
          app: easy-recipes
    template:
      metadata:
            labels:
              app: easy-recipes
      spec:
        containers:
          - name: easy-recipes-container
            image: ram1uj/easy-recipes:latest
            ports:
              - containerPort: 8080
