apiVersion: v1
kind: Service
metadata:
  name: easy-recipes-service
  namespace: dev
spec:
    selector:
        app: easy-recipes
    ports:
        - port: 80
          targetPort: 8080
    type: NodePort